// <auto-generated />
using System;
using MasterDetailApp.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterDetailApp.EF.Migrations
{
    [DbContext(typeof(MasterDetailContext))]
    [Migration("20200218144357_Added100Articles")]
    partial class Added100Articles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasterDetailApp.EF.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 17, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(6932),
                            Description = "Description1",
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 16, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(7934),
                            Description = "Description2",
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 2, 15, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(7985),
                            Description = "Description3",
                            Title = "Title3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 2, 14, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8019),
                            Description = "Description4",
                            Title = "Title4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 13, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8049),
                            Description = "Description5",
                            Title = "Title5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 12, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8088),
                            Description = "Description6",
                            Title = "Title6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 2, 11, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8119),
                            Description = "Description7",
                            Title = "Title7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 10, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8151),
                            Description = "Description8",
                            Title = "Title8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 9, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8182),
                            Description = "Description9",
                            Title = "Title9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 2, 8, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8285),
                            Description = "Description10",
                            Title = "Title10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 7, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8320),
                            Description = "Description11",
                            Title = "Title11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 6, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8351),
                            Description = "Description12",
                            Title = "Title12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 2, 5, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8384),
                            Description = "Description13",
                            Title = "Title13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 2, 4, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8416),
                            Description = "Description14",
                            Title = "Title14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 3, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8448),
                            Description = "Description15",
                            Title = "Title15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 2, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8481),
                            Description = "Description16",
                            Title = "Title16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 2, 1, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8511),
                            Description = "Description17",
                            Title = "Title17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 31, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8545),
                            Description = "Description18",
                            Title = "Title18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 30, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8575),
                            Description = "Description19",
                            Title = "Title19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 29, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8606),
                            Description = "Description20",
                            Title = "Title20"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 28, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8639),
                            Description = "Description21",
                            Title = "Title21"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 27, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8670),
                            Description = "Description22",
                            Title = "Title22"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 26, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8701),
                            Description = "Description23",
                            Title = "Title23"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 25, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8731),
                            Description = "Description24",
                            Title = "Title24"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 24, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8798),
                            Description = "Description25",
                            Title = "Title25"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 23, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8830),
                            Description = "Description26",
                            Title = "Title26"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 22, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8862),
                            Description = "Description27",
                            Title = "Title27"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 21, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8894),
                            Description = "Description28",
                            Title = "Title28"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 20, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8927),
                            Description = "Description29",
                            Title = "Title29"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 19, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8959),
                            Description = "Description30",
                            Title = "Title30"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 18, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(8991),
                            Description = "Description31",
                            Title = "Title31"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 17, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9022),
                            Description = "Description32",
                            Title = "Title32"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 16, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9054),
                            Description = "Description33",
                            Title = "Title33"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 15, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9087),
                            Description = "Description34",
                            Title = "Title34"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 14, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9119),
                            Description = "Description35",
                            Title = "Title35"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 13, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9151),
                            Description = "Description36",
                            Title = "Title36"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 12, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9181),
                            Description = "Description37",
                            Title = "Title37"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 11, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9215),
                            Description = "Description38",
                            Title = "Title38"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 10, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9304),
                            Description = "Description39",
                            Title = "Title39"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 9, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9338),
                            Description = "Description40",
                            Title = "Title40"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 8, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9369),
                            Description = "Description41",
                            Title = "Title41"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2020, 1, 7, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9401),
                            Description = "Description42",
                            Title = "Title42"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 6, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9433),
                            Description = "Description43",
                            Title = "Title43"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 5, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9465),
                            Description = "Description44",
                            Title = "Title44"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 4, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9495),
                            Description = "Description45",
                            Title = "Title45"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 3, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9528),
                            Description = "Description46",
                            Title = "Title46"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 2, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9557),
                            Description = "Description47",
                            Title = "Title47"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2020, 1, 1, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9588),
                            Description = "Description48",
                            Title = "Title48"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 31, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9619),
                            Description = "Description49",
                            Title = "Title49"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 30, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9651),
                            Description = "Description50",
                            Title = "Title50"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 29, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9683),
                            Description = "Description51",
                            Title = "Title51"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 28, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9715),
                            Description = "Description52",
                            Title = "Title52"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 27, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9747),
                            Description = "Description53",
                            Title = "Title53"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 26, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9809),
                            Description = "Description54",
                            Title = "Title54"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 25, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9841),
                            Description = "Description55",
                            Title = "Title55"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 24, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9873),
                            Description = "Description56",
                            Title = "Title56"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 23, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9904),
                            Description = "Description57",
                            Title = "Title57"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 22, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9936),
                            Description = "Description58",
                            Title = "Title58"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 21, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9968),
                            Description = "Description59",
                            Title = "Title59"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 20, 16, 43, 56, 917, DateTimeKind.Local).AddTicks(9998),
                            Description = "Description60",
                            Title = "Title60"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 19, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(30),
                            Description = "Description61",
                            Title = "Title61"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 18, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(63),
                            Description = "Description62",
                            Title = "Title62"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 17, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(95),
                            Description = "Description63",
                            Title = "Title63"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 16, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(122),
                            Description = "Description64",
                            Title = "Title64"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 15, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(154),
                            Description = "Description65",
                            Title = "Title65"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 14, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(186),
                            Description = "Description66",
                            Title = "Title66"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 13, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(277),
                            Description = "Description67",
                            Title = "Title67"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 12, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(311),
                            Description = "Description68",
                            Title = "Title68"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 11, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(342),
                            Description = "Description69",
                            Title = "Title69"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 10, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(375),
                            Description = "Description70",
                            Title = "Title70"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 9, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(406),
                            Description = "Description71",
                            Title = "Title71"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 8, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(439),
                            Description = "Description72",
                            Title = "Title72"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 7, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(472),
                            Description = "Description73",
                            Title = "Title73"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 6, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(503),
                            Description = "Description74",
                            Title = "Title74"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 5, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(534),
                            Description = "Description75",
                            Title = "Title75"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 4, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(565),
                            Description = "Description76",
                            Title = "Title76"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 3, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(597),
                            Description = "Description77",
                            Title = "Title77"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 12, 2, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(625),
                            Description = "Description78",
                            Title = "Title78"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 12, 1, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(655),
                            Description = "Description79",
                            Title = "Title79"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 30, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(686),
                            Description = "Description80",
                            Title = "Title80"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 29, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(718),
                            Description = "Description81",
                            Title = "Title81"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 28, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(783),
                            Description = "Description82",
                            Title = "Title82"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 27, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(817),
                            Description = "Description83",
                            Title = "Title83"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 26, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(848),
                            Description = "Description84",
                            Title = "Title84"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 25, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(878),
                            Description = "Description85",
                            Title = "Title85"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 24, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(908),
                            Description = "Description86",
                            Title = "Title86"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 23, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(938),
                            Description = "Description87",
                            Title = "Title87"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 22, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(968),
                            Description = "Description88",
                            Title = "Title88"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 21, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1001),
                            Description = "Description89",
                            Title = "Title89"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 20, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1032),
                            Description = "Description90",
                            Title = "Title90"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 19, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1065),
                            Description = "Description91",
                            Title = "Title91"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 18, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1096),
                            Description = "Description92",
                            Title = "Title92"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 17, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1126),
                            Description = "Description93",
                            Title = "Title93"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 16, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1160),
                            Description = "Description94",
                            Title = "Title94"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 15, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1193),
                            Description = "Description95",
                            Title = "Title95"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 14, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1221),
                            Description = "Description96",
                            Title = "Title96"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2019, 11, 13, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1304),
                            Description = "Description97",
                            Title = "Title97"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 12, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1342),
                            Description = "Description98",
                            Title = "Title98"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 11, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1371),
                            Description = "Description99",
                            Title = "Title99"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2019, 11, 10, 16, 43, 56, 918, DateTimeKind.Local).AddTicks(1399),
                            Description = "Description100",
                            Title = "Title100"
                        });
                });

            modelBuilder.Entity("MasterDetailApp.EF.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2020, 2, 18, 16, 43, 56, 907, DateTimeKind.Local).AddTicks(6082),
                            Name = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2020, 2, 18, 16, 43, 56, 914, DateTimeKind.Local).AddTicks(293),
                            Name = "Category2"
                        });
                });

            modelBuilder.Entity("MasterDetailApp.EF.Article", b =>
                {
                    b.HasOne("MasterDetailApp.EF.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
